language: android
jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/3.*.*
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository

script: TERM=dumb ./gradlew check assembleDebug

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file_glob: true
  file: build/outputs/*.aar
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - ./gradlew bintrayUpload
